FROM ubuntu:22.04

# install app
COPY ./modules /app/modules
COPY ./main.py /app
COPY ./requirements.txt /app

WORKDIR /app

# install app dependencies
RUN apt-get update && apt-get install -y python3 python3-pip
RUN pip install -r requirements.txt

# final configuration
EXPOSE 5000
CMD flask run --host 0.0.0.0 --port 5000